remote_theme: pmarsceill/just-the-docs

title: SPACEDOS02
description: Solid-state PIN diode dosimeter for manned spacecraft. Liulin detector replacement.

permalink: pretty

gh_edit_link: true # show edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/UniversalScientificTechnologies/SPACEDOS02" # the github URL for your repo
gh_edit_branch: "SPACEDOS02B" # the branch that your docs is served from
gh_edit_source: "/" # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
